language: node_js
node_js:
  - "11"

script:
  - npm run build

deploy:
  provider: pages
  local_dir: public
  # Don't remove build artifacts
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    # All development is done on `develop`
    branch: develop
  # User pages must be published to `master`
  target-branch: master
